### Before you do these

I wrote a simple script that should populate a universal test, train, and toy set. Run that script first if you'd like to clean small set of data

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/lee/practice/big_data/reddit-comments-kaggle/data/toy.csv', sep='\t', encoding='utf-8', engine='python')

df.head(5)

,Unnamed: 0,Unnamed: 0.1,created_utc,ups,subreddit_id,link_id,name,score_hidden,author_flair_css_class,author_flair_text,...,downs,archived,author,score,retrieved_on,body,distinguished,edited,controversiality,parent_id
0,2243084,4098,1433086769,8,t5_2qh3s,t3_37y00u,t1_crqvs5d,0,NaN,NaN,...,0,0,infinitysgame,8,1433498416,"""Cage goes in the water, you go in the water. ...",NaN,0,0,t1_crqvo4g
1,1977930,2385,1432750820,2,t5_2qh3s,t3_37gsou,t1_crmqlii,0,NaN,NaN,...,0,0,Lechatestdanslefrigo,2,1433298721,"20 years after the first movie, and we're on t...",NaN,0,0,t3_37gsou
2,841616,2481,1431414009,2,t5_2qh33,t3_35mw4d,t1_cr6cq9y,0,NaN,NaN,...,0,0,Liberalguy123,2,1432909666,Where I live in California there are a lot of ...,NaN,0,0,t1_cr65g80
3,1046504,326,1431654399,1,t5_2qh33,t3_35z3hq,t1_cr9kapx,0,NaN,NaN,...,0,0,rannie_pophe,1,1433071058,And be paranoid of sirens...,NaN,0,0,t1_cr9gewp
4,555457,2926,1431050694,1,t5_2qh33,t3_358vip,t1_cr240xr,0,NaN,NaN,...,0,0,agarring,1,1432836297,Captions say it all. Mhm. Yep.,NaN,0,0,t1_cr23zsa

In [6]:
df = df[['body', 'parent_id']]

In [8]:
def comment_under_post(row):
    return row["parent_id"].startswith("t1")

df["comment_under_post"] = df.apply(lambda row: comment_under_post(row), axis=1)

In [15]:
df = df[df.body != '[deleted]']

In [23]:
delim = ["&gt;", "\n"]

for dlm in delim:
    df.body = df.body.str.replace(dlm, '')

,body,parent_id,comment_under_post
1969,Nestle's CEO is the same dude who believes tha...,t1_crg8iew,True
1970,"""ER""",t1_cqusd10,True
1971,"jesus, 15 yearsOW MY GROIN!",t3_360jt3,False
1972,Love of Sir Patrick Stewart is never to be moc...,t3_36tyuk,False
1973,Yet people are making ends meet in every city ...,t1_criibxh,True
1974,And to allow a goal is just the ultimate feeli...,t1_cqvfpe3,True
1975,"Fucking love Phil Jones, I reckon he could be ...",t3_369th3,False
1976,Depending on which version of the 10 Commandme...,t1_crhvlyq,True
1977,And sucks.,t1_crcjtpx,True
1978,And they never saw him again.,t3_37mv5d,False
1979,Chances that Hillary actually does something ...,t1_cr0ypp5,True
1980,Autism woman would be the worst super hero ever.,t3_36n82j,False
1981,And apparently Peter Pan kidnaps kids and take...,t3_35995v,False
1982,not that cheap $50/year is insanely cheap. He ...,t1_craovev,True
1984,I just made it up on my lunch break at work be...,t1_cqufhue,True
1985,Never understood what makes Spiders scary. The...,t3_359vw9,False
1986,As much as I loved Pi and all the innovations ...,t1_crl2fph,True
1987,"Haven't read the article, but from contemporan...",t1_cro0n4s,True
1988,"This comment deserves 17,000 upvotes",t1_cr436fx,True
1989,Congrats haha. It seemed fitting to make fun o...,t1_cqytxne,True
1990,riding on a scorpion sounds like terrible idea...,t3_3622mc,False
1991,Frames as light as 600grams are available. You...,t1_cre2l0y,True
1992,"Mort is definitely the superior book, hands do...",t1_crk5o0t,True
1993,This one time I attended a pop-up restaurant t...,t3_37t8cw,False
1994,That's what 90% of the people using the chair ...,t1_cr2f8tf,True
1995,Yeah I feel that bro. I'm not really the type ...,t1_cr6obra,True
1996,We should take away the best moments of people...,t1_crorhmw,True
1997,I see a nice attempt at autonomy. But from my ...,t3_3798c5,False
1998,"Well, the lack of call of duty is good, but ze...",t1_crdrnjy,True
1999,But on your way from one side of a galaxy to t...,t1_cqvqi48,True