## Intro

This is a great place to get started on the project. With this notebook, you can explore the dataset a lot more easily than with a command line.

**Be sure to have run the ```createdataset.py``` script first.**

As a note: the below ```pd.read_csv()``` function has a quick fix in the parameters. Ideally, we would be using the C engine, but there is a bug with the csv file that we need to fix. The python engine seems to be working fine, but it will slower.

In [1]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv('project/data/subreddit_subset.csv',encoding='utf-8', engine='python')

In [25]:
df.describe()

,Unnamed: 0,created_utc,ups,subreddit_id,link_id,name,score_hidden,author_flair_css_class,author_flair_text,subreddit,...,downs,archived,author,score,retrieved_on,body,distinguished,edited,controversiality,parent_id
count,2261363,2271842,2272190,2272190,2272190,2271842,2271842,22518,22710,2271842,...,2271842,2271842,2271842,2271842,2271842,2271799,18486,2271494,2271494,2271494
unique,5413,1468766,2556,12,88999,2260943,2,330,835,10,...,2,2,435562,2545,497667,2009675,3,64177,3,969930
top,1514,created_utc,1,t5_2qh33,t3_363d2m,name,0,author_flair_css_class,author_flair_text,funny,...,0,0,[deleted],1,retrieved_on,[deleted],distinguished,0,0,parent_id
freq,520,10900,925635,745916,14300,10900,2260942,10900,10900,745916,...,2260942,2260942,203190,925635,10900,187129,10900,2195519,2163033,10900

In [24]:
df.head(5)

,Unnamed: 0,created_utc,ups,subreddit_id,link_id,name,score_hidden,author_flair_css_class,author_flair_text,subreddit,...,downs,archived,author,score,retrieved_on,body,distinguished,edited,controversiality,parent_id
0,54,1430438402,2,t5_2qh3s,t3_34fdua,t1_cqug91y,0,NaN,NaN,movies,...,0,0,[deleted],2,1432703080,[deleted],NaN,0,0,t1_cqug49i
1,67,1430438402,-11,t5_2qh3l,t3_34f1lq,t1_cqug92b,0,NaN,NaN,news,...,0,0,hogsucker,-11,1432703080,1-She got to be a bigwig at Google by sleeping...,NaN,0,0,t1_cqu4t11
2,70,1430438402,2,t5_2qh3s,t3_34cvv6,t1_cqug92e,0,NaN,NaN,movies,...,0,0,PoopyVampire,2,1432703080,"Holy shit, I couldn't tell if some of those sc...",NaN,0,0,t3_34cvv6
3,95,1430438403,16,t5_2qh03,t3_34fcd4,t1_cqug934,0,NaN,NaN,gaming,...,0,0,fusaaa,16,1432703080,All the ghosts are running even though they ar...,NaN,0,0,t1_cquf52p
4,103,1430438403,1,t5_2qh03,t3_34crmu,t1_cqug93c,0,NaN,NaN,gaming,...,0,0,[deleted],1,1432703080,"Sweet , great Idea there as well",NaN,0,0,t1_cqttge6